### ISSUE TITLE
Introduction to git and GitHub

### ISSUE THREAD

**Issue by kdillmcfarland** [rladies-seattle/rladies-seattle-organizing#15]
# Introduction to git and GitHub

### Who is the audience?

* Anyone interested in using distributed version control
* Researchers, students, etc

### Why is this important?

* Version control helps you and others use your code now and in the future

### What should be covered?

* Command line git file tracking
* GitHub file sharing/storage
* A git GUI and/or git in RStudio
* Branches and merge conflicts? (I think this should probably be in a second intermediate session)

### Suggested speakers or contributors

* Me!
* Anyone familiar with the Carpentries git content would be most appreciated as a co-lead

### Resources you would recommend to the audience

* Intro command line http://swcarpentry.github.io/shell-novice/
* Installing git https://git-scm.com/downloads
* Intro to git (some of which will be used in this event) http://swcarpentry.github.io/git-novice/

### Suggested time

* It's a lot of content so I think multiple sessions are needed. Maybe 2 or 3 lunches?

**Comment by monicagerber** [comment]
Thanks for initiating this @kdillmcfarland! @katiejolly and I were thinking that there is a lot of unmet demand for git content!

I would love to co-teach an intro to git course for beginners following [the Carpentries lesson](https://swcarpentry.github.io/git-novice/). I think this would have to be in the evening because we need at least 2 hours.

And I would love to see a "version control with R" series for 2021 with beginner, intermediate, and advanced topics. I have some ideas for some intermediate topics, but may think it out in a blog post first.

**Comment by kdillmcfarland** [comment]
Maybe a lunch time series? I love the accessibility of lunch time meetups and we could each take lead on one plus recruit others for later ones. Could do 1hr chunks like

* git (init, commits, checkout)
* github (fetch, pull, online interface)
* git GUI and in Rstudio
* git collaboration (branches, merge conflicts)

**Comment by katiejolly** [comment]
One of the women I work with is interested in doing a session on an intermediate/advanced topic! We were thinking something like GitHub actions or another CI topic. Maybe that’ll be good after this series :)

**Comment by monicagerber** [comment]
It looks like the [Carpentries lesson](https://swcarpentry.github.io/git-novice/) is 3 hours long and covers most of what you've listed, @kdillmcfarland. We could do 3 lunchtime sessions of 1 hour each. Although I wonder how challenging that would be in an online environment (rather than classroom). Do you know of anyone doing intro git classes online right now? Maybe something more specific to using git with R? I don't want to have to re-create the curriculum!

**Comment by kdillmcfarland** [comment]
I do like the lunchtime series idea. Carpentries is all remote now and it goes pretty smoothly (I've heard from other instructors). Key changes that help are (1) open office hour(s) the day before to help with any install issues (2) an instructor dedicated to chat monitoring, (3) giving a bit more time (everything just seems to take a little longer remote esp if you use breakout rooms). 

So we could start with their content I think. The outline I had before as in ~1hrs chunks.

**Comment by monicagerber** [comment]
Oops, sorry @kdillmcfarland I did not see your 1hr suggestion at first! Do you want to take the lead on this intro series? I could sign on as a co-lead, but would be great to get 1-2 more people to help with sessions.

**Comment by monicagerber** [comment]
Lead, as in get us organized for the intro series, and assign us to co-teach or lead individual sessions. :)

**Comment by kdillmcfarland** [comment]
Absolutely! Since we have a Feb event scheduled, perhaps reproducible March, one a week for the month?

**Comment by monicagerber** [comment]
Thanks to some discussions on R-Ladies Seattle Slack, this will be scheduled for April. 

@kdillmcfarland, I created a folder on google drive to help organize us. Will share with you.
